VENV := scripts/.venv
PYTHON := $(VENV)/bin/python

.PHONY: venv publications serve build deploy

venv:
	@test -d $(VENV) || python3 -m venv $(VENV)
	@$(PYTHON) -m pip install --quiet -r scripts/requirements.txt

publications: venv
	@$(PYTHON) scripts/build_publications.py

serve: publications
	hugo server -D

build: publications
	hugo --gc --cleanDestinationDir

# Builds locally to catch errors early, stages and commits all changes with an
# autogenerated message, then pushes to master. GitHub Actions
# (.github/workflows/deploy.yml) rebuilds and publishes to GitHub Pages on push.
deploy: build
	git add -A
	@if git diff --cached --quiet; then \
		echo "Nothing to commit."; \
	else \
		files=$$(git diff --cached --name-only | tr '\n' ' '); \
		git commit -m "Update: $$files"; \
	fi
	git push origin master
